# Generated by Django 5.2.5 on 2025-09-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='John', max_length=50, null=True),
        ),
    ]
