# Generated by Django 5.2.5 on 2025-09-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rating_newspage_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('news_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.newspage')),
            ],
        ),
    ]
