# Generated by Django 5.2.5 on 2025-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(default='avatar.jpeg', upload_to=''),
        ),
    ]
